import { useSelector, useDispatch } from "react-redux";
import { useEffect } from "react";
import { reset, setToken, getUser } from "../features/auth/authSlice";
import { useRouter } from "next/router";

import Head from "next/head";
import Dashboard from "../components/Dashboard";
import Layout from "../components/ui/Layout";

export default function Home() {

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Dashboard></Dashboard>
      </Layout>
    </>
  );
}
